
DECLARE 
	V_NAME VARCHAR2(30);
    v_salary number;
	CURSOR C1 IS SELECT FIRST_NAME, salary
					FROM EMPLOYEES
					WHERE DEPARTMENT_ID = 60;
BEGIN	
	OPEN C1;
		LOOP
			FETCH C1 INTO V_NAME, v_salary;
            DBMS_OUTPUT.PUT_LINE(V_NAME||' '||v_salary);
			EXIT WHEN C1%NOTFOUND;	
		END LOOP;	
	CLOSE C1;
END;
/
