
DECLARE 
	V_NAME VARCHAR2(30);
	CURSOR C1 IS SELECT FIRST_NAME
					FROM EMPLOYEES
					WHERE DEPARTMENT_ID = 60;
BEGIN	
	OPEN C1;
		LOOP
			FETCH C1 INTO V_NAME;
            DBMS_OUTPUT.PUT_LINE(V_NAME);
			EXIT WHEN C1%NOTFOUND;	
		END LOOP;	
	CLOSE C1;
END;
/
