
DECLARE 
	V_NAME EMPLOYEES.FIRST_NAME%TYPE;
	V_SALARY EMPLOYEES.SALARY%TYPE;
	V_HDATE EMPLOYEES.HIRE_DATE%TYPE;
	
	CURSOR C1 IS SELECT FIRST_NAME, SALARY, HIRE_DATE
					FROM EMPLOYEES
					WHERE DEPARTMENT_ID = 60;
BEGIN	
	OPEN C1;
		LOOP
			FETCH C1 INTO V_NAME, V_SALARY, V_HDATE;
			EXIT WHEN C1%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(V_NAME||' '||V_SALARY||' '||V_HDATE);
		END LOOP;	
	CLOSE C1;
EXCEPTION 
	WHEN OTHERS THEN 
		DBMS_OUTPUT.PUT_LINE('ERROR FOUND');
END;
/
